  version: "2.18"

  services:
    localstack:
      image: localstack/localstack:latest
      ports:
        - "${LOCALSTACK_PORT}:${LOCALSTACK_PORT}"
      environment:
        GATEWAY_LISTEN: "0.0.0.0:${LOCALSTACK_PORT}"
        LOCALSTACK_HOST: "localstack:${LOCALSTACK_PORT}"
        SERVICES: "dynamodb,s3"
        EAGER_SERVICE_LOADING: "1"
        DEBUG: "false"
        LS_LOG: "trace"
        DOCKER_HOST: "unix:///var/run/docker.sock"
      ulimits:
        nofile:
          soft: 20000
          hard: 40000
      networks:
        - internal

  networks:
    internal:
